homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    
]

jadwal/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'jadwal'

urlpatterns = [
    path('', views.jadwal, name='jadwal'),
    url(r'(?P<pk>[0-9]+)/delete/$', views.JadwalDelete.as_view(), name='delete'),
]

test_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('jadwal/', include('jadwal.urls')),
    
    
]

homepage/models.py
from django.db import models

# Create your models here.

jadwal/models.py
from django.db import models
# from django.forms import ModelForm


class Form(models.Model):
    
    #hari = 
    tanggal= models.DateField(blank=True, null=True)
    jam = models.TimeField()
    kegiatan = models.CharField(max_length=50)
    tempat = models.CharField(max_length=50)
    kategori = models.CharField(max_length=50)

# def __str__(self):
#     return self.name

jadwal/forms.py
from django import forms
from .models import Form


class PostForm(forms.ModelForm):
    class Meta:
        model = Form
        fields = '__all__'
        widgets = {
            'tanggal' : forms.SelectDateWidget(),
            'jam' : forms.TimeInput(attrs={
                'class' : 'form-control',
                'type' : 'time'
            }),
        }

homepage/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def contact(request):
    return render(request, 'contact.html')

# Create your views here.

jadwal/views.py
from django.shortcuts import render, redirect
from .forms import PostForm
from .models import Form
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy

class JadwalDelete(DeleteView):
        model = Form
        success_url = reverse_lazy('jadwal:jadwal')

def jadwal(request):
    post = Form.objects.all()
    post_form = PostForm(request.POST or None)


    if request.method == 'POST':
        # if 'id' in request.POST:
        #     Form.objects.get(id=request.POST['id']).delete()
        #     return redirect('jadwal:jadwal')
        
        if post_form.is_valid():
            post_form.save()
            return redirect('jadwal:jadwal')

    context = {
        'post_form' : post_form,
        'posting': post 
    }
    return render(request, 'jadwal.html',context)

homepage/templates/about.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <title>Website Wildan</title>
    <link rel="stylesheet" href= "{% static "css/mystyle.css" %}">
    <link rel="stylesheet" href= "{% static "css/bootstrap.css" %}">
    <style>
        
        .body{
            background-image: url("{% static "images/background2 (2).jpg" %}");
        }   
        .menubar{
            background-color: #F9B77B;
        }

    </style>
</head>
<body>
    <section class= "body">
        <img src="{% static "images/skills.png" %}" id="skill";>
        <div>
            <img src="{% static "images/wildan.jpg" %}" class="image";>
        </div>
        <div>
            <img src="{% static "images/about.png" %}" id="desc";>
        </div>
    <div class="menubar">
        <a href="{% url 'homepage:home' %}">Home</a>
        <a href="{% url 'homepage:about' %}">About</a>
        <a href="{% url 'homepage:contact' %}">Contact</a>
        <a href="{% url 'jadwal:jadwal' %}">Jadwal</a>
    </div>
    </section>
</body>
</html>

homepage/templates/contact.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Website Wildan</title>
    <link rel="stylesheet" href= "{% static "css/mystyle.css" %}">
    <link rel="stylesheet" href= "{% static "css/bootstrap.css" %}">
    <style>
        body{
            background-image: url("{% static "images/background32.jpg" %}");
            background-repeat: no-repeat;
 
        }
        .menubar{
            background-color: #AE9CB2;
        }

    </style>
</head>
<body>
    <section class = "body">
    <img src="{% static "images/contact.png" %}" id="contact";>
    <div class="menubar">
        <a href="{% url 'homepage:home' %}">Home</a>
        <a href="{% url 'homepage:about' %}">About</a>
        <a href="{% url 'homepage:contact' %}">Contact</a>
        <a href="{% url 'jadwal:jadwal' %}">Jadwal</a>
    </div>
    <div>
        <div class= "follow">Follow me on :</div>
        <div><a class= "twitterlogo" href= "https://twitter.com/m_wildan80"><img src= "{% static "images/twitter.png" %}"> </a></div>
        <div><a class= "iglogo" href= "https://www.instagram.com/m_wildan80"><img src= "{% static "images/ig(2).png" %}"> </a></div>
        <div class= "twitter">Twitter</div>
        <div class= "ig">Instagram</div>
        <div class= "username">@m_wildan80</div>
    </div>
    </section>
</body>
</html>

homepage/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <title>Website Wildan</title>
    <link rel="stylesheet" href= "{% static "css/mystyle.css" %}">
    <link rel="stylesheet" href= "{% static "css/bootstrap.css" %}">
    <style>
       
        .body{
            background-image: url("{% static "images/background12.jpg" %}");
        }   
        .menubar{
            background-color: #373737;    
        }
        .menubar a{
                color: #ffffff;
        }
    </style>
</head>
<body>
    <section class = "body">
        <img src= "{% static "images/heywildan.png" %}" class="centertext";>
    <div class="menubar">
            <a href="{% url 'homepage:home' %}">Home</a>
            <a href="{% url 'homepage:about' %}">About</a>
            <a href="{% url 'homepage:contact' %}">Contact</a>
            <a href="{% url 'jadwal:jadwal' %}">Jadwal</a>
    </div>
    </section>
</body>


</html>

jadwal/templates/jadwal.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    
    <title>Website Wildan</title>
    <link rel="stylesheet" href= "{% static "css/mystyle.css" %}">
    <link rel="stylesheet" href= "{% static "css/bootstrap.css" %}">
    <style>
          
        .menubar{
            background-color: #373737;    
        }
        .menubar a{
                color: #ffffff;
        }
        .body1{
            background-color: #69bcd1; 
        }
        th {
        text-align: center;
        }
        table#t01 {  
        border: 1px solid black;
        border-collapse: collapse;
        }
        
    </style>
</head>
<body class= "body1">
        <form action="" method="POST"style="margin: 10vw 10vw">
            {% csrf_token %}
            <table>
                {{post_form.as_table}}
            </table>
            <button type="submit">Submit</button>
        </form>
        <div class="centertext">
        <table style="width: 100%; margin-left: 40vw; border: 1px solid black" id= "t01">
            <tr>
                <th style= "border: 1px solid black; padding: 5px 25px">Tanggal</th>
                <th style= "border: 1px solid black; padding: 5px 25px">Pukul</th> 
                <th style= "border: 1px solid black; padding: 5px 25px">Kegiatan</th>
                <th style= "border: 1px solid black; padding: 5px 25px">Tempat</th>
                <th style= "border: 1px solid black; padding: 5px 25px">Kategori</th>
            </tr>
        </table>
        </div>
        <br>
        
        {% for a in posting %}
        <table style= "margin-left: 40vw; border: 1px solid black" id="t01">
            
            <tr>
                <td style= "border: 1px solid black; padding: 5px 10px">{{a.tanggal}}</td>
                <td style= "border: 1px solid black; padding: 5px 10px">{{a.jam}}</td>
                <td style= "border: 1px solid black; padding: 5px 10px">{{a.kegiatan}}</td>
                <td style= "border: 1px solid black; padding: 5px 10px">{{a.tempat}}</td>
                <td style= "border: 1px solid black; padding: 5px 10px">{{a.kategori}}</td>
                <!-- <div>
                    <form method="POST" action="">
                        {% csrf_token %}
                        <input name="id" value="{{i.id}}" type="hidden">
                        <button type="submit" value="Submit" class="btn btn-primary mx-auto mt-2" style="font-size: 0.8rem;">Delete</button>
                    </form>
                </div> -->
                <form action="{% url 'jadwal:delete' a.id %}" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="a_id" value="{{ a.id }}"/>
                    <button type="" class="btn-sm col-2" style="margin-left: 80vw;" >
                     Hapus
                    </button> 
                </form>
            </tr>
        <br>
        </table>
        
        {% endfor %}
    <div class="menubar">
            <a href="{% url 'homepage:home' %}">Home</a>
            <a href="{% url 'homepage:about' %}">About</a>
            <a href="{% url 'homepage:contact' %}">Contact</a>
            <a href="{% url 'jadwal:jadwal' %}">Jadwal</a>
    </div>
</body>


</html>